// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp3nL1-hFo8K2hO_Ho2kOetZ0UqBavq4g',
    appId: '1:673334063908:android:218355c75d1ec3cbcdf9b1',
    messagingSenderId: '673334063908',
    projectId: 'movie-search-app-bc014',
    storageBucket: 'movie-search-app-bc014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiFDPkRE7tmZFMSknXatdZecePMIQS1eM',
    appId: '1:673334063908:ios:6104c06b79cb2beccdf9b1',
    messagingSenderId: '673334063908',
    projectId: 'movie-search-app-bc014',
    storageBucket: 'movie-search-app-bc014.appspot.com',
    iosBundleId: 'com.example.movieSearchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiFDPkRE7tmZFMSknXatdZecePMIQS1eM',
    appId: '1:673334063908:ios:06898f7476f93552cdf9b1',
    messagingSenderId: '673334063908',
    projectId: 'movie-search-app-bc014',
    storageBucket: 'movie-search-app-bc014.appspot.com',
    iosBundleId: 'com.example.movieSearchApp.RunnerTests',
  );
}
